### ISSUE TITLE
Requesting a non-existent codemod should be a warning and not a hard error

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#346]
https://github.com/pixee/codemodder-specs/pull/18

**Comment by clavedeluna** [comment]
A warning but continue running with all codemods? Or what should replace `CLI error: argument --codemod-include: invalid choice(s): ...`?

**Comment by drdavella** [comment]
So I think if `--codemod-include` is given a non-existent codemod, we should get a warning like "Requested codemod `foo:bar/baz` does not exist" and it should just be ignored. And we should get a similar warning for `--codemod-exclude`.

**Comment by clavedeluna** [comment]
@drdavella  refining logic question:  what is your expected logic if you run `codemodder tests/samples/ --output here.txt --codemod-include=bad1,bad2`, where none of the codemods requested exist. Should it run all default codemods or not run anything? I think it should not run anything, because the same example but with `codemod-exclude` is more clear:

if `codemodder tests/samples/ --output here.txt --codemod-exclude=bad1,bad2 ` runs, where the requested excluded codemods don't match anything, we should run all default codemods since nothing was excluded.

**Comment by drdavella** [comment]
@clavedeluna I think you're right; it should exit cleanly without doing anything (but critically it should still generate CodeTF if requested).

**Comment by drdavella** [comment]
Just to clarify: I think this should be implemented without any explicit shortcut logic since I think the rest will just fall out as a consequence of having no codemods to run. If that makes any sense.

**Comment by clavedeluna** [comment]
@drd See https://github.com/pixee/codemodder-python/issues/377 which is related
