### ISSUE TITLE
Sonar: fix SQL injection with `sql-parameterization`

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#375]
https://rules.sonarsource.com/python/RSPEC-3649/

**Comment by clavedeluna** [comment]
This turned out to be harder than just adding a sonar codemod for the existing codemodder sql-parametrization codemod:
1. sonar does not seem to create a vulnerability finding for any sqlite3 code with `+` str concat while the sql codemod we currently have does support this
2. the sqlite3 non-compliant example [sonar provides here](https://rules.sonarsource.com/python/RSPEC-3649/) doesn't make our codemod fire. At a glance, you think it would since it uses `%` to create the query (our tests show we handle this) but perhaps it requires more tweaking of the codemod. I also tried to give sonar some of our examples with `%` but it didn't find them.
