### ISSUE TITLE
Failure to parse `requirements.txt` files with `-r` flags

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#400]
## Background
It's possible to link to other `requirements.txt` files using the `-r` flag:
```
# requirements.txt
-r path/to/other/requirements.txt
```

We currently fail to account for such cases and we fail to update dependencies.

## Definition of Done
* Parse `requirements.txt` files with `-r` flag without errors
* Successfully add new dependencies to such files

**Comment by clavedeluna** [comment]
Right now a requirements.txt file with a `-r` line will indeed fail with `packaging.requirements.InvalidRequirement: Expected package name at the start of dependency specifier` and codemodder will entirely disregard this requirement.txt file, which is not good at all. A bug indeed. Fixing this by simply ignoring any `-r ...` lines should be straight-forward enough and fix this bug.

However, to fully support `-r ...` lines would be a feature with much higher scope. Right now the repo manager assumes an ordered hierarchy for dependency stores (_potential_stores). It would take some effort to change this to allow for the flexibility of  `_potential_stores` that it could be TWO+ requirements.txt files which could change. Right now codemodder has this strict definition:
> For now just pick the first store found with order given by _potential_stores.

which means that after finding one dependency store file, for example a project.toml, even if there is a requirements.txt file (lower in the hierarchy), we won't update requirements.txt.

So to support updating any two+ dependency stores (requirements.txt with -r lines, or any combo of dependency stores), we would need to do quite a bit. Here's what I can think that at least needs to change in the requirements.txt with -r lines at least:
1. Assuming `RequirementsTxtParser` no longer fails at `-r` lines, it should now also detect these lines and create  additional `PackageStore` instances for each of these lines, each pointing to the right file path with the right dependencies inside it.
2. `PythonRepoManager` needs to be updated accordingly so that `self._potential_stores` may have multiple dependency stores, not just `self._potential_stores` with the `[0]` assumption
3.  When a codemod that run wants to add a new dependency to the project, `DependencyManager.write` runs. This method needs to now account for the possibility of multiple dependency store files that exist. Where should we add the new dependency? In the original requirements.txt file which had the -r line or in the file pointed to by -r? It needs to check all of these dependency store files to make sure we don't add the dependency if it already exists.

This last part is going to be tricky. We should really tackle [this PR](https://github.com/pixee/codemodder-python/pull/237) first?

**Comment by drdavella** [comment]
@clavedeluna good points, but I want to keep the scope of this pretty narrow right now. I just want to make sure we don't fail to parse files with `-r` and that we can successfully add dependencies to such files when necessary. We don't need it to be any more complicated than that right now.
